'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_HISTORY_LOADING = 'history/GET_HISTORY_LOADING';
var GET_HISTORY_SUCCESS = 'history/GET_HISTORY_SUCCESS';
var GET_HISTORY_ERROR = 'history/GET_HISTORY_ERROR';

exports.GET_HISTORY_LOADING = GET_HISTORY_LOADING;
exports.GET_HISTORY_SUCCESS = GET_HISTORY_SUCCESS;
exports.GET_HISTORY_ERROR = GET_HISTORY_ERROR;