'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_HOME_PLAYLIST_LOADING = 'home/GET_HOME_PLAYLIST_LOADING';
var GET_HOME_PLAYLIST_SUCCESS = 'home/GET_HOME_PLAYLIST_SUCCESS';
var GET_HOME_PLAYLIST_ERROR = 'home/GET_HOME_PLAYLIST_ERROR';

var GET_HOME_VIDEO = 'home/GET_HOME_VIDEO';
var UPDATE_ACTIVE_PLAYLIST = 'home/UPDATE_ACTIVE_PLAYLIST';

exports.GET_HOME_PLAYLIST_LOADING = GET_HOME_PLAYLIST_LOADING;
exports.GET_HOME_PLAYLIST_SUCCESS = GET_HOME_PLAYLIST_SUCCESS;
exports.GET_HOME_PLAYLIST_ERROR = GET_HOME_PLAYLIST_ERROR;
exports.GET_HOME_VIDEO = GET_HOME_VIDEO;
exports.UPDATE_ACTIVE_PLAYLIST = UPDATE_ACTIVE_PLAYLIST;