'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_MOVIE_STREAM_LOADING = 'movie-detail/GET_MOVIE_STREAM_LOADING';
var GET_MOVIE_STREAM_SUCCESS = 'movie-detail/GET_MOVIE_STREAM_SUCCESS';
var GET_MOVIE_STREAM_ERROR = 'movie-detail/GET_MOVIE_STREAM_ERROR';

exports.GET_MOVIE_STREAM_LOADING = GET_MOVIE_STREAM_LOADING;
exports.GET_MOVIE_STREAM_SUCCESS = GET_MOVIE_STREAM_SUCCESS;
exports.GET_MOVIE_STREAM_ERROR = GET_MOVIE_STREAM_ERROR;