'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_MOVIE_LIBRARY_LOADING = 'movie-library/GET_MOVIE_LIBRARY_LOADING';
var GET_MOVIE_LIBRARY_SUCCESS = 'movie-library/GET_MOVIE_LIBRARY_SUCCESS';
var GET_MOVIE_LIBRARY_ERROR = 'movie-library/GET_MOVIE_LIBRARY_ERROR';

exports.GET_MOVIE_LIBRARY_LOADING = GET_MOVIE_LIBRARY_LOADING;
exports.GET_MOVIE_LIBRARY_SUCCESS = GET_MOVIE_LIBRARY_SUCCESS;
exports.GET_MOVIE_LIBRARY_ERROR = GET_MOVIE_LIBRARY_ERROR;