'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_MOVIE_DETAIL_LOADING = 'movie-detail/GET_MOVIE_DETAIL_LOADING';
var GET_MOVIE_DETAIL_SUCCESS = 'movie-detail/GET_MOVIE_DETAIL_SUCCESS';
var GET_MOVIE_DETAIL_ERROR = 'movie-detail/GET_MOVIE_DETAIL_ERROR';

exports.GET_MOVIE_DETAIL_LOADING = GET_MOVIE_DETAIL_LOADING;
exports.GET_MOVIE_DETAIL_SUCCESS = GET_MOVIE_DETAIL_SUCCESS;
exports.GET_MOVIE_DETAIL_ERROR = GET_MOVIE_DETAIL_ERROR;