'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_HOT_PLAYLIST_LOADING = 'not-found/GET_HOT_PLAYLIST_LOADING';
var GET_HOT_PLAYLIST_SUCCESS = 'not-found/GET_HOT_PLAYLIST_SUCCESS';
var GET_HOT_PLAYLIST_ERROR = 'not-found/GET_HOT_PLAYLIST_ERROR';

exports.GET_HOT_PLAYLIST_LOADING = GET_HOT_PLAYLIST_LOADING;
exports.GET_HOT_PLAYLIST_SUCCESS = GET_HOT_PLAYLIST_SUCCESS;
exports.GET_HOT_PLAYLIST_ERROR = GET_HOT_PLAYLIST_ERROR;