'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var GET_SEARCH_LOADING = 'search/GET_SEARCH_LOADING';
var GET_SEARCH_SUCCESS = 'search/GET_SEARCH_SUCCESS';
var GET_SEARCH_NO_RESULT = 'search/GET_SEARCH_NO_RESULT';
var GET_SEARCH_ERROR = 'search/GET_SEARCH_ERROR';

var GET_SEARCH_GENRE_LOADING = 'search/GET_SEARCH_GENRE_LOADING';
var GET_SEARCH_GENRE_SUCCESS = 'search/GET_SEARCH_GENRE_SUCCESS';
var GET_SEARCH_GENRE_ERROR = 'search/GET_SEARCH_GENRE_ERROR';

var GET_RECENT_SEARCH_LOADING = 'search/GET_RECENT_SEARCH_LOADING';
var GET_RECENT_SEARCH_SUCCESS = 'search/GET_RECENT_SEARCH_SUCCESS';
var GET_RECENT_SEARCH_ERROR = 'search/GET_RECENT_SEARCH_ERROR';

var DELETE_RECENT_SEARCH = 'search/DELETE_RECENT_SEARCH';

exports.GET_SEARCH_GENRE_LOADING = GET_SEARCH_GENRE_LOADING;
exports.GET_SEARCH_GENRE_SUCCESS = GET_SEARCH_GENRE_SUCCESS;
exports.GET_SEARCH_GENRE_ERROR = GET_SEARCH_GENRE_ERROR;
exports.GET_SEARCH_LOADING = GET_SEARCH_LOADING;
exports.GET_SEARCH_SUCCESS = GET_SEARCH_SUCCESS;
exports.GET_SEARCH_ERROR = GET_SEARCH_ERROR;
exports.GET_SEARCH_NO_RESULT = GET_SEARCH_NO_RESULT;
exports.GET_RECENT_SEARCH_LOADING = GET_RECENT_SEARCH_LOADING;
exports.GET_RECENT_SEARCH_SUCCESS = GET_RECENT_SEARCH_SUCCESS;
exports.GET_RECENT_SEARCH_ERROR = GET_RECENT_SEARCH_ERROR;
exports.DELETE_RECENT_SEARCH = DELETE_RECENT_SEARCH;