'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SET_USER_VARIABLE = 'SET_USER_VARIABLE';

var UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
var UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
var UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

var UPDATE_SETTING_REQUEST = 'UPDATE_SETTING_REQUEST';
var UPDATE_SETTING_SUCCESS = 'UPDATE_SETTING_SUCCESS';
var UPDATE_SETTING_FAILURE = 'UPDATE_SETTING_FAILURE';

exports.SET_USER_VARIABLE = SET_USER_VARIABLE;
exports.UPDATE_PROFILE_REQUEST = UPDATE_PROFILE_REQUEST;
exports.UPDATE_PROFILE_SUCCESS = UPDATE_PROFILE_SUCCESS;
exports.UPDATE_PROFILE_FAILURE = UPDATE_PROFILE_FAILURE;
exports.UPDATE_SETTING_REQUEST = UPDATE_SETTING_REQUEST;
exports.UPDATE_SETTING_SUCCESS = UPDATE_SETTING_SUCCESS;
exports.UPDATE_SETTING_FAILURE = UPDATE_SETTING_FAILURE;