const GET_HISTORY_LOADING = 'history/GET_HISTORY_LOADING';
const GET_HISTORY_SUCCESS = 'history/GET_HISTORY_SUCCESS';
const GET_HISTORY_ERROR = 'history/GET_HISTORY_ERROR';

export { GET_HISTORY_LOADING, GET_HISTORY_SUCCESS, GET_HISTORY_ERROR };
