const GET_HOME_PLAYLIST_LOADING = 'home/GET_HOME_PLAYLIST_LOADING';
const GET_HOME_PLAYLIST_SUCCESS = 'home/GET_HOME_PLAYLIST_SUCCESS';
const GET_HOME_PLAYLIST_ERROR = 'home/GET_HOME_PLAYLIST_ERROR';

const GET_HOME_VIDEO = 'home/GET_HOME_VIDEO';
const UPDATE_ACTIVE_PLAYLIST = 'home/UPDATE_ACTIVE_PLAYLIST';

export {
  GET_HOME_PLAYLIST_LOADING,
  GET_HOME_PLAYLIST_SUCCESS,
  GET_HOME_PLAYLIST_ERROR,
  GET_HOME_VIDEO,
  UPDATE_ACTIVE_PLAYLIST,
}
