const GET_MOVIE_LIBRARY_LOADING = 'movie-library/GET_MOVIE_LIBRARY_LOADING';
const GET_MOVIE_LIBRARY_SUCCESS = 'movie-library/GET_MOVIE_LIBRARY_SUCCESS';
const GET_MOVIE_LIBRARY_ERROR = 'movie-library/GET_MOVIE_LIBRARY_ERROR';
const GET_MOVIE_LIBRARY_LIST_LOADING =
  'movie-library/GET_MOVIE_LIBRARY_LIST_LOADING';
const GET_MOVIE_LIBRARY_LIST_SUCCESS =
  'movie-library/GET_MOVIE_LIBRARY_LIST_SUCCESS';
const GET_MOVIE_LIBRARY_LIST_ERROR =
  'movie-library/GET_MOVIE_LIBRARY_LIST_ERROR';

export {
  GET_MOVIE_LIBRARY_LOADING,
  GET_MOVIE_LIBRARY_SUCCESS,
  GET_MOVIE_LIBRARY_ERROR,
  GET_MOVIE_LIBRARY_LIST_LOADING,
  GET_MOVIE_LIBRARY_LIST_SUCCESS,
  GET_MOVIE_LIBRARY_LIST_ERROR
};
