const GET_MOVIE_STREAM_LOADING = 'movie-detail/GET_MOVIE_STREAM_LOADING';
const GET_MOVIE_STREAM_SUCCESS = 'movie-detail/GET_MOVIE_STREAM_SUCCESS';
const GET_MOVIE_STREAM_ERROR = 'movie-detail/GET_MOVIE_STREAM_ERROR';

export {
  GET_MOVIE_STREAM_LOADING,
  GET_MOVIE_STREAM_SUCCESS,
  GET_MOVIE_STREAM_ERROR
}
