const GET_MOVIE_LIBRARY_LOADING = 'movie-library/GET_MOVIE_LIBRARY_LOADING';
const GET_MOVIE_LIBRARY_SUCCESS = 'movie-library/GET_MOVIE_LIBRARY_SUCCESS';
const GET_MOVIE_LIBRARY_ERROR = 'movie-library/GET_MOVIE_LIBRARY_ERROR';

export {
  GET_MOVIE_LIBRARY_LOADING,
  GET_MOVIE_LIBRARY_SUCCESS,
  GET_MOVIE_LIBRARY_ERROR
}
