const GET_MOVIE_DETAIL_LOADING = 'movie-detail/GET_MOVIE_DETAIL_LOADING';
const GET_MOVIE_DETAIL_SUCCESS = 'movie-detail/GET_MOVIE_DETAIL_SUCCESS';
const GET_MOVIE_DETAIL_ERROR = 'movie-detail/GET_MOVIE_DETAIL_ERROR';

export {
  GET_MOVIE_DETAIL_LOADING,
  GET_MOVIE_DETAIL_SUCCESS,
  GET_MOVIE_DETAIL_ERROR
}
