const GET_HOT_PLAYLIST_LOADING = 'not-found/GET_HOT_PLAYLIST_LOADING';
const GET_HOT_PLAYLIST_SUCCESS = 'not-found/GET_HOT_PLAYLIST_SUCCESS';
const GET_HOT_PLAYLIST_ERROR = 'not-found/GET_HOT_PLAYLIST_ERROR';

export {
  GET_HOT_PLAYLIST_LOADING,
  GET_HOT_PLAYLIST_SUCCESS,
  GET_HOT_PLAYLIST_ERROR
};
